# Generated by Django 3.0.5 on 2020-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0005_groupmemberrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
