# Generated by Django 3.0.5 on 2020-05-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0007_shoppinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
