# Generated by Django 3.0.5 on 2020-05-31 01:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftlist', '0009_shoppinglist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('member', 'group')},
        ),
    ]
