# Generated by Django 3.0.5 on 2020-05-31 01:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftlist', '0010_auto_20200531_0147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmemberrequest',
            unique_together={('to_group', 'from_user')},
        ),
    ]
