# Generated by Django 3.0.5 on 2020-11-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0011_auto_20200531_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='available',
            new_name='selected',
        ),
    ]
