# Generated by Django 3.0.5 on 2020-11-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0012_auto_20201103_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='selected',
            new_name='available',
        ),
    ]
