# Generated by Django 3.0.5 on 2020-11-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0013_auto_20201103_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='available',
            new_name='selected',
        ),
    ]
